name: Publicar
on: push

jobs:
  PsGallery:
    name: PsGallery 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish
        shell: pwsh
        run: ./publish.ps1