name: Publicar
on: push

jobs:
  PsGallery:
    name: PsGallery 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch tags
        run: git fetch --prune --unshallow --tags
      - name: Publish
        shell: pwsh
        run: ./publish.ps1