name: TestPowershai
on: 
    workflow_call:
        secrets:
            HuggingFaceToken:
            OpenaiToken:
            GoogleApiToken:
        inputs:
            TestModels:
                required: true
                type: string

jobs:
  PsGallery:
    name: PsGallery 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch tags
        run: git fetch --prune --unshallow --tags
      - name: Test
        shell: pwsh
        env:
          HF_API_TOKEN: ${{ secrets.HuggingFaceToken }}
          OPENAI_API_KEY: ${{ secrets.OpenaiToken }}
          GOOGLE_API_KEY: ${{ secrets.GoogleApiToken }}
          POWERSHAI_TEST_MODELS: ${{ inputs.TestModels }}
        run: ./util/publish-prepare.ps1 -BasicTest